# Generated by Django 3.1.6 on 2021-02-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210221_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='pub_date',
        ),
    ]
