# Generated by Django 3.1.6 on 2021-02-22 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_thought_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 4, 47, 8, 942291, tzinfo=utc)),
        ),
    ]
