# Generated by Django 3.1.6 on 2021-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
