# Generated by Django 3.1.6 on 2021-02-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210219_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='thought_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='thought',
            name='title_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
